server:
  port: 8001

spring:
  
  application:
    name: ms-product
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-product
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
    
springdoc:

  title: "Product Api"
  description: "Api for product"
  version: "v1.0.0"
  contact-name: "Jean Ramal"
  contact-email: "jean.ramal@codearti.com"
  contact-url: "https://www.codearti.com"
  
  api-docs:
    path: /api-docs
#  packages-to-scan:
#  - com.codearti.application.rest
#  paths-to-match:
#  - /v1
  swagger-ui:
    path: /swagger-ui.html
#    operations-sorter: alpha